---
- name: Install dependencies 
  dnf: 
    name: 
      - firewalld 

- name: Ensure firewalld is started 
  service: 
    name: firewalld
    state: started
  changed_when: false
 
- name: Configure firewall rules 
  firewalld:
      zone: public
      service: "{{ item }}"
      permanent: yes
      state: enabled
  notify: reload firewalld
  loop:
    - https
    - http
    - ssh
    - mysql
