---
# tasks file for install-vncserver

- name: Install tigervnc-server for RedHat
  yum:
    name:
      - xorg-x11-fonts-Type1
      - tigervnc-server
      - tigervnc-server-module
      - tigervnc
    state: present
  when: ( ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Rocky" ) and
        ( vncserver is not defined or vncserver == "tiger" )

- name: Install tigervnc-server for Debian
  apt:
    name:
      - tigervnc-standalone-server
      - tigervnc-xorg-extension
      - tigervnc-viewer
    state: present
  when: ansible_facts['os_family'] == "Debian" and
        ( vncserver is not defined or vncserver == "tiger" )

- name: Install tightvnc-server for Debian
  apt:
    name:
      - xfce4
      - xfce4-goodies
      - tightvncserver
    state: present
  when: ansible_facts['os_family'] == "Debian" and
        vncserver is defined and
        vncserver == "tight"
        
- name: Install tightvnc-server for RedHat
  fail:
    msg: "We do not have ansible tasks configured for installing tightvnc server on RedHat based systems. We suggest you set the variable vncserver: tiger"
  when: ansible_facts['os_family'] == "Debian" and
        vncserver is defined and
        vncserver == "tight"
        
- name: Add group 'vncusers'
  ansible.builtin.group:
    name: vncusers
    state: present

- name: Copy over vncadmin
  copy:
    src: vncadmin
    dest: /usr/sbin/vncadmin
    mode: u=rx
    owner: root
    group: root

- name: Copy over vncctl
  copy:
    src: vncctl
    dest: /usr/bin/vncctl
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root

- name: Copy over vncctl to sudoers.d
  copy:
    src: vncctl.sudoers.d
    dest: /etc/sudoers.d/vncctl
    mode: u=rw,g=r,o=r
    owner: root
    group: root

- name: Add admin users to vnc
  command:
    cmd: /usr/sbin/vncadmin add {{ item }}
  with_items:
    - demeler
    - gegorbet
    - alexey
    - ehb
  ignore_errors: yes
  