branch: "{{ us3_branch }}"

cron_enable_dev: 'no'
cron_enable_update_notice: 'no'
cron_enable_pro: 'yes'

submit_dir: '/srv/www/htdocs/uslims3/uslims3_data'

class_dir_p: '/srv/www/htdocs/common/class/'
class_dir_d: '/srv/www/htdocs/common/class_devel/'
class_dir_l: '/srv/www/htdocs/common/class_local/'

org_name: 'Ultrascan3 Admin'
org_domain: '{{ ansible_domain }}'

time_zone: 'America/Chicago'
gridctl_admin_email: "us3-admin@biophysics.uleth.ca"

serviceURL: "http://gridfarm005.ucs.indiana.edu:8080/ogce-rest/job"
serviceURL2: "http://gridfarm005.ucs.indiana.edu:8080/ogce-rest/job"
