---
language: python
services:
  - docker
install:
  - pip install molecule docker
env:
  global: 
    - MOLECULE_DISTRO: centos8 

  matrix: 
    - ROLE_NAME: config-lims-apache
    - ROLE_NAME: config-lims-php
    - ROLE_NAME: config-lims-lims
    - ROLE_NAME: config-lims-slurm
    - ROLE_NAME: config-lims-us3-user
    - ROLE_NAME: config-lims-database
    - ROLE_NAME: config-lims-firewall


before_script: 
  - cd ${TRAVIS_BUILD_DIR}/roles/${ROLE_NAME} 
 
script: 
  - molecule test 

on:
  branch: master
