---
- hosts: example-host
  remote_user: usadmin

  pre_tasks:
# uncomment to get all ansible_facts for target host
#      - name: Print all available facts
#        ansible.builtin.debug:
#          var: ansible_facts

      - name: set www_user for Debian
        set_fact:
          www_user: "www-data"
        when: ansible_os_family == "Debian"

      - name:  set www_user for RedHat
        set_fact:
          www_user: "apache"
        when: ansible_os_family == "RedHat"

      - name: disable selinux
        selinux:
           state: disabled

      - name: update system
        yum: name=* state=latest
        when: ansible_facts['os_family'] == "RedHat"

      - name: install EPEL repo for CentOS
        yum: name=epel-release state=present
        when: ansible_facts['distribution'] == "CentOS"

      - name: enable codeready for RedHat
        command:
           cmd: subscription-manager repos --enable "codeready-builder-for-rhel-8-x86_64-rpms"
        when: ansible_facts['distribution'] == "RedHat"

      - name: enable codeready for Oracle
        command:
           cmd: dnf config-manager --set-enabled ol8_codeready_builder
        when: ansible_facts['distribution'] == "OracleLinux"

      - name: install EPEL repo for RedHat
        yum:
           name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
           state: present
        when: ansible_facts['distribution'] == "RedHat" or ansible_os_family == "Rocky" or ansible_facts['distribution'] == "OracleLinux"

  roles:
      - config-lims-gui
      - config-lims-admin
      - config-lims-firewall
      - config-lims-repo
      - config-lims-us3-user
      - config-lims-database
      - config-lims-apache
      - config-lims-php
      - config-lims-lims
      - config-lims-slurm
      - build-qt
      - build-qwt
      - build-us3
      - build-us-mpi
      - install-vncserver
      - install-postfix
      - install-chrony
      - install-google-fonts
      - install-msttcore-fonts
      - install-reverse-tunnel
      - renice-mariadb
      - renice-slurmd
      - restart-php-fpm
      - install-demo-dbinst
      - config-lims-backup
      - install-xrdp
      - install-proxychains4
      - install-fail2ban
      - config-lims-scigap
      
  become: yes
  vars:
        - install_workstation: false
        - install_commercial: true

        # set the desired compiler optimization
        # for hardware installs
        - comp_opt: "-march=native"
        # perhaps for VM installs if qt core dumps
        # - comp_opt: "-m64"
        
        # innodb_buffer_pool_size
        - innodb_buffer_pool_size: "2G"
        # - innodb_buffer_pool_size: "8G"

        # uncomment one of the below for default allowed submissions
        - submit_localonly: true
        # - submit_remoteonly : true
        # - submit_localandremote : true

        # Required variables to define:
        # N.B. once you set these, you can't change them simply by rerunning ansible-playbook for the same remote host!
        - us3_db_pass: "foobar-demo"
        - root_db_pass: "foobar-super"
        - admins_db_pass: "foobar-admin"
        - gbl_db_pass: "foobar-global"
        - us3php_db_pass: "foobar-php"
        - limsadmin_db_pass: "foobar-iam-admin" 

        - admin_email: "example@email.org"
        - cron_admin: "example@email.org" # root@localhost 
        
        - ipaddr_ext: "192.168.5.30"
        - ipaddr_int: "192.168.5.30"
        
        - self_signed: 'yes' # change to 'no' to use certbot 

        - qt_major_version: "5.14"
        - qt_version: "5.14.2"
        - qwt_version: "6.1.5"
        - cores_for_parallel_compile: 4
        - us3_branch: "master"
        - gridctl_branch: "master"
        - common_branch: "master"
        - newinst_branch: "master"
        - webinfo_branch: "master"
        - utils_branch: "main"

        - postfix_relay_smtp_host: smtp.gmail.com
        - postfix_relay_smtp_port: 587
        - postfix_relay_smtp_user: us.etc.tests@gmail.com
        - postfix_relay_smtp_password: put_app_password_here

        # required if install-reverse-tunnel role run
        # you will manually need to install usadmin's public key on the rtunnel_user @ rtunnel_ip's authorized keys
        - rtunnel_user: "ultrascan"
        - rtunnel_ip: "142.66.17.9"
        # assign unique port
        - rtunnel_port: "220XX"

        # set this to a specific value (could be numeric ip) instead of {{ ansible_fqdn }} if you with, e.g. if the host is private
        # N.B. you can only configure one host per ansible-playbook run if you do not use {{ ansible_fqdn }}
        - hostname: "{{ ansible_fqdn }}"
        - postfix_hostname: "{{ hostname }}"
        # N.B. if your host name is pure ip (e.g. 1.2.3.4 etc), you need to configure a text string prefix as commented below
        # - postfix_hostname: "us-{{ hostname }}"

        # Doesn't matter if self-signed is enabled but here as an example for some certbot uses
        - certbot_create_if_missing: true
        - certbot_admin_email: "{{ admin_email }}" 
        - certbot_create_standalone_stop_services: [httpd] # centos/RHEL 
        - certbot_certs: 
            - domains: 
                  - "{{ hostname }}" 

        - certbot_auto_renew: true 
        - certbot_auto_renew_hour: "1" 
        - certbot_auto_renew_minute: "30" 
        - cerbot_auto_renew_options: "--quiet --no-self-upgrade"

        - slurm_ver: 20.02.7 # Change to appropriate version 
        - slurm_md5: e47e68692354f03db2999ec84fe3f735

        # N.B. slurm_cores can not exceed available cores, if it does, the node will be stuck "draining" (waiting for available resources)
        #      if you want to develop (not production!) on a smaller system
        #         add "#SBATCH -O" to your sbatch submission scripts to allow overcommitting
        #         set - slurm_sbatch_extras : "#SBATCH -O\n" for slurm testing scripts via ansible
        - slurm_cores : 2
        - slurm_sbatch_extras : ""
        # - slurm_sbatch_extras : "#SBATCH -O\n"

        # Overrride variables that are default
        - lims_admin: "John Smith"
        - org_name: "Ultrascan Example LIMS"

