---
# We do this because no default passwords are supplied
- name: assert password variables are defined
  assert:
     that:
       - us3_db_pass is defined
       - gbl_db_pass is defined
       - admins_db_pass is defined
#       - root_db_pass is defined
       - limsadmin_db_pass is defined

- name: install depedencies
  dnf:
    name:
      - git

# Create ini file
- name: Create LIMS ini file
  template:
      src: ini-template.j2
      dest: "{{ ini_cfg_path }}"
      owner: us3
      group: apache
      mode: "0640"

# Common dir.
- name: Clone commons repo
  git:
   repo: "{{ common_url }}"
   dest: "{{ www_common }}"
   version: "{{ branch }}"

# Web info dir.
- name: clone webinfo repo
  git:
   repo: "{{ webinfo_url }}"
   dest: "{{ www_uslims }}"
   version: "{{ branch }}"

- name: Template webinfo config
  template:
    src: "webinfo-config.php.j2"
    dest: "{{ www_uslims }}/config.php"
    backup: yes

# Newlims dir.
- name: Clone newinst repo
  git:
    repo: "{{ newinst_url }}"
    version: "{{ branch }}"
    dest: "{{ www_newlims }}"

- name: Template newinst config
  template:
    src: "newinst-config.php.j2"
    dest: "{{ www_newlims }}/config.php"
    backup: yes

# looks like one day if we complain enough, git will support chowning within the git module
# https://github.com/ansible/ansible/issues/51601
#
- name: change permissions because ansible >:(
  file:
    path: "{{ www_base }}"
    owner: "us3"
    group: "apache"
    recurse: yes
    state: directory
  changed_when: false
