apache_user: us3
apache_group: apache 
www_base: "/srv/www/htdocs" 
www_uslims: "{{ www_base }}/uslims3" 
ssl_key_path: "/etc/letsencrypt/live/{{ server_name }}/privkey.pem"
ssl_cert_path: "/etc/letsencrypt/live/{{ server_name }}/fullchain.pem" 
ssl_self_base_path: "/etc/httpd/ssl" 
ssl_self_key_path: "{{ ssl_self_base_path }}/self-priv.key" 
ssl_self_csr_path: "{{ ssl_self_base_path }}/self-csr.key" 
ssl_self_cert_path: "{{ ssl_self_base_path }}/self-cert.key" 
server_admin: "demeler@gmail.com" 
server_name: "{{ ansible_fqdn }}" 
self_signed: 'no'
certbot_admin_email: "{{ admin_email }}" 
certbot_create_if_missing: true 
certbot_create_method: 'standalone' 
certbot_create_standalone_stop_services: httpd 
certbot_certs: 
        - domains: 
              - "{{ server_name }}" 
