---

- name: Check if qwt already installed, using /opt/qt-{{ qt_version }}-qwt-{{ qwt_version }}/lib/libqwt.so as a proxy
  stat: 
    path: /opt/qt-{{ qt_version }}-qwt-{{ qwt_version }}/lib/libqwt.so
  register: qwt_installed_details

- name: Install, configure and compile qwt
  block:
    - name: Check if qwt-{{ qwt_version }}.tar.bz2 is downloaded
      stat:
        path: /opt/qwt-{{ qwt_version }}.tar.bz2
      register: qwt_src_details

    - name: Download qwt-{{ qwt_version }}
      get_url: 
#        url: https://sourceforge.net/project/qwt/files/qwt/{{ qwt_version }}/qwt-{{ qwt_version }}.tar.bz2/download
#        url: https://gigenet.dl.sourceforge.net/project/qwt/qwt/{{ qwt_version }}/qwt-{{ qwt_version }}.tar.bz2
        url: https://versaweb.dl.sourceforge.net/project/qwt/qwt/{{ qwt_version }}/qwt-{{ qwt_version }}.tar.bz2
        dest: /opt/qwt-{{ qwt_version }}.tar.bz2

      when: qwt_src_details.stat.exists == false

    - name: Check if qwt-{{ qwt_version }}.tar.bz2 is extracted
      stat:
        path: /opt/qt-{{ qt_version }}-qwt-{{ qwt_version }}/qwt.pro
      register: qwt_src_extracted_details

    - name: Create a directory if it does not exist
      file:
        path: /opt/qt-{{ qt_version }}-qwt-{{ qwt_version }}
        state: directory
        mode: '0755'
      when: qwt_src_extracted_details.stat.exists == false
              
    - name: Extract qwt-{{ qwt_version }}
      command:
        chdir: /opt/qt-{{ qt_version }}-qwt-{{ qwt_version }}
        cmd: tar jxf /opt/qwt-{{ qwt_version }}.tar.bz2 --strip-components=1 
        warn: false
      when: qwt_src_extracted_details.stat.exists == false

    - name: Configure qwt
      shell:
        chdir: /opt/qt-{{ qt_version }}-qwt-{{ qwt_version }}
        cmd: /opt/qt-{{ qt_version }}/bin/qmake qwt.pro

    - name: Compile qwt for RedHat using gcc-9
      shell:
        chdir: /opt/qt-{{ qt_version }}-qwt-{{ qwt_version }}
        cmd: . /opt/rh/gcc-toolset-9/enable && gcc -v 2> build.gccversion && make -j {{ cores_for_parallel_compile }} > build.stdout 2> build.stderr
      when: ansible_facts['os_family'] == "RedHat"

    - name: Compile qwt for Debian
      shell:
        chdir: /opt/qt-{{ qt_version }}-qwt-{{ qwt_version }}
        cmd: gcc -v 2> build.gccversion && make -j {{ cores_for_parallel_compile }} > build.stdout 2> build.stderr
      when: ansible_facts['os_family'] == "Debian"

#    - name: install qwt
#      shell:
#        chdir: /tmp/qwt-{{ qwt_version }}
#        cmd: make install 
#      when: false == true

  when: qwt_installed_details.stat.exists == false
