---
- name: install php related dependencies
  dnf:
      enablerepo: PowerTools
      name: "{{ packages }}"

- name: Check if magik already exists
  stat:
        path: /usr/lib64/php/modules/imagick.so
  register: imagick_module

- name: Install magik
  shell: echo '' | /usr/bin/pecl install imagick
  when: imagick_module.stat.exists == false

- name: Configure php.ini
  copy:
        src: php.ini
        dest: /etc/php.ini
        backup: yes
  notify: restart php-fpm


- name: Configure php-fpm.conf
  copy:
        src: php-fpm.conf
        dest: /etc/php-fpm.conf
        backup: yes
  notify: restart php-fpm

- name: Configure www.conf
  copy:
        src: www.conf
        dest: /etc/php-fpm.d/www.conf
        backup: yes
  notify: restart php-fpm
